# Generated by Django 5.0.2 on 2024-03-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customuser_is_superuser'),
    ]

    operations = [
    ]
