# Generated by Django 5.0.2 on 2024-03-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('diet', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('no_preference', 'No Preference')], max_length=15)),
            ],
        ),
    ]
